# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: daa474a38b023580c6d988fb0a3a37794450f42bd013667db2dfd2ae28552aeca66e8171ce269bdcb377aa883f4ada1b358319fd0c8c7e9d19ccfe7ca076267a

test:
  secret_key_base: f7cb66e04e77047927734004fef4df5745d4b732525b41bad15e59459b39ca4c538d961ac65e0d8a4d3c10948b612eedfed5e0fc63275d6131ecd99b5623710a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
